travis:
  secure:
    BINSTAR_TOKEN: 0twmAiZsx4aMmhn4qbdF8pIpdIviZcpx9UtPFdDOvZPiR8tNkpGpnD/BFaZN5hdlDw4uc7u+GjnvVfk0fE5IxMpG3eaQToHvSJY0eiWUInSx6VUV+Zyv/MP1ln7mrHujE2V83dEaoaanhViWo8HyQa2KAWmZjPECNBbkOhgdj+buS/2JhOyLbY5h8erOJEbRVeCmmEctqlO7wasgoXrkP3cUxCB15o+jJ2zLCxIEED8PMMZmLf3jtxlfwJdou5w4kqXlp8lsf8T1kVS7bgD3glJVxlJPH0/rjHHr6kmYmxFeQkbEyhQwidOuRAuVUOtNM2DaF9vJDaDz+L2gxJmllyGh9AZ2sXAxeSp+TD8mnMkTpaalPumIQIKcbUZmQOFkJjOq94/7IS/sHVhD5jyJqfJ8GXrGQ4etq6kXHntH7wMDgbMs+Jc+OufIliTH1TbIXbmJqda97r47bSZyrJzvpnjm0IWI9UfttHyuaj2t3mnpJt5hQuBfzCdpLo2oOVs/WRjCD5kkI/6Sh28B5mXdqZ12XwM0f+HnWwvnW1DODbfKKlS3Yr9lVSrT9q11EIkWJU1KXjnSThk248O9U0h8rXUNECf+12MT+7wrKbYFT+PAlPDONpp7K7H/iyK+Odr5FCI4kBFkALA6hs0xSw5wjUxKdBEj7q7gQMVy9aASZ3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
