travis:
  secure:
    BINSTAR_TOKEN: DAkbtfVLEcDMoPdAcN+RG9uhhLNH7cloZZt/w/Q4hw0kQE40cm3m03vceHPNP1P9/kYwGKUMDKZsGUFLqr+h3Tkm6Xt6SlR7R6TQobtj4aQYDq5OPwKTf23djw9TP6rD4/WD0UcYAt8Ja4cNcMbPs7PR6TPZ0Z5LgBpiFSuhO2d+jnrIyWYuk2Ay7y8h4jjl52bw8YjU3w57YaMuMZsYmydPoLTyR+R1z2HtmwN4wAjkgH26DsiflGCbYnlRSGNf3ioG5JV2EuiWsxpq9nsHV3nGMqvLOZGz2XnPQq0udyXc/fnIDWyVp7+8eR16jcd7UOfhYGEYx8T0kP4CqfY43MJLpIf7sUdTa7FRuzPmCuZU3w21R5wyu51KmOiNSC4cS1Ujm3OM1xK8cEtBbGV69XyUtrVxGcBz3u984HVfRcY6U38yP0bEwluDOIGfl1w9/2XxyNQLeFH6qAohGjswnjx1FqQ3G5TfOeIjbQw0R5fMLtF7h6tLJf9eeBlKiZ056AgEVScm2cAbESkyiBfgsniqweY5m8FPZxO/QCFRSsGnS0OjCxHFEcZAV9w/oVXzW7o1l6xIwXnxcJu2kT6jkIfyC+LWYkyKmXQx6l6dpx9/snUCKT2xMPeAzI5H4SyckilT+cx+Jm4h0vWKBeQOTyfHnYPepCiwVTU3KL1xv8c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
